[install]
cmds = ["npm install --legacy-peer-deps"]

[setup]
nodeCanvasDependencies = ["python3", "pkg-config", "pixman", "cairo", "pango", "libjpeg", "giflib", "librsvg"]

[deploy]
startCommand = "bash start.sh"
